"""E01 S06 seed derivation and lossless trajectory serialization.

This package defines reconstruction infrastructure only.  It neither resolves
the author/MATLAB RNG ambiguity nor selects a downstream state-sampling instant.
"""

from .provenance import (
    EXPECTED_REGISTRY_SHA256,
    EXPECTED_RUNTIME_FINGERPRINT,
    capture_identity_from_workspace,
    file_sha256,
    package_source_sha256,
    registry_boundary_from_workspace,
    repository_head,
)
from .seed import (
    BIT_GENERATOR_NAME,
    CANONICAL_JSON_VERSION,
    CANONICAL_STREAM_PURPOSES,
    SEED_DERIVATION_ALGORITHM,
    SEED_SCHEMA_VERSION,
    CouplingPolicy,
    DerivedStream,
    SeedBundle,
    SeedContractError,
    SeedRequest,
    StreamPurpose,
    canonical_json_bytes,
    derive_seed_bundle,
    isolated_stream_namespace,
    seed_request_from_payload,
    sha256_hex,
)
from .serialization import (
    SerializationError,
    deserialize_envelope,
    float_bits_hex,
    float_from_hex,
    float_to_hex,
    make_envelope,
    serialize_envelope,
    validate_json_schema,
    verify_envelope,
)
from .trajectory import (
    PRECISION_CONTRACT_VERSION,
    SPECIFICATION_PAYLOAD_VERSION,
    TRAJECTORY_SCHEMA_VERSION,
    CaptureIdentity,
    RegistryBoundary,
    TrajectoryContractError,
    binary64_ulp_distance,
    capture_independent_trajectory,
    payload_sha256,
    regenerate_independent_trajectory,
    specification_from_payload,
    specification_to_payload,
    validate_trajectory_invariants,
)

__all__ = [
    "BIT_GENERATOR_NAME",
    "CANONICAL_JSON_VERSION",
    "CANONICAL_STREAM_PURPOSES",
    "EXPECTED_REGISTRY_SHA256",
    "EXPECTED_RUNTIME_FINGERPRINT",
    "PRECISION_CONTRACT_VERSION",
    "SEED_DERIVATION_ALGORITHM",
    "SEED_SCHEMA_VERSION",
    "SPECIFICATION_PAYLOAD_VERSION",
    "TRAJECTORY_SCHEMA_VERSION",
    "CaptureIdentity",
    "CouplingPolicy",
    "DerivedStream",
    "RegistryBoundary",
    "SeedBundle",
    "SeedContractError",
    "SeedRequest",
    "SerializationError",
    "StreamPurpose",
    "TrajectoryContractError",
    "binary64_ulp_distance",
    "canonical_json_bytes",
    "capture_identity_from_workspace",
    "capture_independent_trajectory",
    "derive_seed_bundle",
    "deserialize_envelope",
    "file_sha256",
    "float_bits_hex",
    "float_from_hex",
    "float_to_hex",
    "isolated_stream_namespace",
    "make_envelope",
    "package_source_sha256",
    "payload_sha256",
    "regenerate_independent_trajectory",
    "registry_boundary_from_workspace",
    "repository_head",
    "seed_request_from_payload",
    "serialize_envelope",
    "sha256_hex",
    "specification_from_payload",
    "specification_to_payload",
    "validate_json_schema",
    "validate_trajectory_invariants",
    "verify_envelope",
]

__version__ = "1.0.0"
